### PR TITLE
Added image viewer component

### PR DESCRIPTION
**Pull request by LuanHimmlisch**
Added a new component with the libraries needed from [waynegm/imgViewer2](https://github.com/waynegm/imgViewer2) and [Leaflet/Leaflet](https://github.com/Leaflet/Leaflet).

I removed accidentally two of the components from the docs but re-added them again and added a link to the new component on the index.

### CODE REVIEW

**Comment by LuanHimmlisch** [comment]
@cesaramirez

**Comment by cesaramirez** [comment]
Gracias @LuanHimmlisch, en proceso de revisión.

**Comment by cesaramirez** [comment]
No tengo comentarios.

**Comment by cesaramirez** [comment]
@skalero01  parece que no tengo permisos para realizar Pull Requests
image

**Pull request merged**
